"""Completion Tools:

Completion tools are tools that are used by the completion agents to mark the task as successful or failed.
In addition to specifying which agents are automatically assigned completion tools, we can control which completion
tools are generated for a task using the 'completion_tools' parameter. This parameter allows us to specify whether we 
want to provide success and/or failure tools, or even provide custom completion tools.

The available options for 'completion_tools' are:
- 'SUCCEED': Generates a tool for marking the task as successful.
- 'FAIL': Generates a tool for marking the task as failed.

If 'completion_tools' is not specified, both 'SUCCEED' and 'FAIL' tools are generated by default.
We can also manually create completion tools and provide them to our agents by calling 'task.get_success_tool()' and 'task.get_fail_tool()' methods."""


import os
import controlflow as cf
from langchain_openai import ChatOpenAI
from dotenv import load_dotenv, find_dotenv

load_dotenv(find_dotenv())

story_writer = cf.Agent(
    name="Short Story Writer",
    model=ChatOpenAI(
        model="gpt-4o-mini",
        openai_api_key=os.getenv("OPENAI_API_KEY")
    )
)

# Generate both success and failure tools (default behavior, equivalent to `completion_tools=None`)
task1 = cf.Task(
    objective="Write a short story about a detective. Do not exceed 100 words.",
    agents=[story_writer],
    completion_tools=["SUCCEED", "FAIL"],
)

# result1 = task1.run()
# print(result1)

# Only generate a success tool
task2 = cf.Task(
    objective="Write a short story about a duck. Do not exceed 100 words.",
    agents=[story_writer],
    completion_tools=["SUCCEED"],
)

# result2 = task2.run()
# print(result2)

# Only generate a failure tool
task3 = cf.Task(
    objective="Write a short story about a eagle. Do not exceed 100 words.",
    agents=[story_writer],
    completion_tools=["FAIL"],
)

# result3 = task3.run()
# print(result3)

# Don't generate any completion tools
task4 = cf.Task(
    objective="Write a short story about AI. Do not exceed ",
    agents=[story_writer],
    completion_tools=[],
)

result4 = task4.run()
print(result4)